### ISSUE TITLE
cyclic dependency on itself

### ISSUE THREAD

**Issue by stardust85** [testing-cabal/extras#8]
I have a library which uses something from extras in its setup.py.

My lib has this in setup.py:
```
from extras import RunFlakesCommand

setup(
    name='mylib',
    packages=find_packages(),
    setup_requires=['extras'],
    tests_require=tests_require,
    cmdclass={'flakes': RunFlakesCommand},
)
```
then when I run
```
python setup.py test
```

I get this error:

```
Traceback (most recent call last):
  File "setup.py", line 51, in <module>
    cmdclass={'flakes': RunFlakesCommand},
  File "/usr/lib64/python2.6/distutils/core.py", line 113, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python2.6/site-packages/setuptools/dist.py", line 268, in __init__
    self.fetch_build_eggs(attrs['setup_requires'])
  File "/usr/lib/python2.6/site-packages/setuptools/dist.py", line 312, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 846, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 1091, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 1103, in obtain
    return installer(requirement)
  File "/usr/lib/python2.6/site-packages/setuptools/dist.py", line 379, in fetch_build_egg
    return cmd.easy_install(req)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 639, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 669, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 852, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 1080, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 1066, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 242, in run_setup
    raise
  File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 141, in resume
    compat.reraise(type, exc, self._tb)
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 239, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 269, in run
    return func()
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 238, in runner
    _execfile(setup_script, ns)
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-Ssf68p/extras-0.0.3/setup.py", line 8, in <module>
    'README.rst'))
AttributeError: 'module' object has no attribute 'try_import'
```

**Comment by rbtcollins** [comment]
I think you have two different extras involved here? RunFlakesCommand isn't part of extras :- but your code got past that, so you must have another module / package providing 'extras', and easy-install has then gotten *this* extras for you, which can't access its actual contents, since your local one has shadowed it.
